# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c31cd973f13d8bde4569ee1720ae6449552212e26cf5f538fef270e0af885962773121974130a0128944cefe00a3ba93e39f75fc2df2f2c1be237a187eef6c71

test:
  secret_key_base: f4d3b9cc1ef315b74c77733e792bc7eb4d5cd385056e309e22b6c6a41bd20aeaa590c82b0d6910a8b89ae9499bb8e8c9c6e668c365fe9285d16a2f36bff9bd8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
